jobs:
  build:
    docker:
      - image: circleci/openjdk:stretch
    working_directory: ~/backend/JavaWebServices
    steps:
      - checkout:
          path: ~/backend/JavaWebServices
      - run: mvn test
