jobs:
  build:
    docker:
      - image: circleci/openjdk:stretch
    working_directory: ~/Team-A-Agile/backend/JavaWebService
    steps:
      - checkout:
          path: ~/Team-A-Agile
      - run: mvn test
