jobs:
  build:
    docker:
      - image: circleci/openjdk:stretch
    working_directory: ~/Team-A-Agile/backend/JavaWebService
    steps:
      - run: java --version
      - checkout:
          path: ~/Team-A-Agile
      - run: 
        name: Install dependencies
        command: mvn clean install
      - run: 
        name: Run unit tests
        command: mvn test
