jobs:
  build:
    docker:
      - image: circleci/openjdk:stretch
    working_directory: ~/Team-A-Agile/backend/JavaWebService
    steps:
      - run: java --version
      - checkout:
          path: ~/Team-A-Agile
      - run: mvn clean install
      - run: mvn test
